apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: immersion-bot
  name: immersion-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immersion-bot
  template:
    metadata:
      labels:
        app: immersion-bot
    spec:
      revisionHistoryLimit: 2
      imagePullSecrets:
        - name: regcred
      containers:
        - image: immersion-bot
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: immersion-bot-secrets-b2gck5m769
                  key: TOKEN
          name: immersion-bot
          ports:
            - name: http
              containerPort: 8080
