apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: immersion-bot
  name: immersion-bot
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: immersion-bot
  template:
    metadata:
      labels:
        app: immersion-bot
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: immersion-bot
          envFrom:
            - configMapRef:
                name: immersion-bot-config
          name: immersion-bot
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: immersion-bot
  name: immersion-bot
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: immersion-bot
  type: ClusterIP
