apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- immersion-bot.yaml
namespace: discord
images:
- name: immersion-bot
  newName: ghcr.io/brigadasos/immersion-bot
  newTag: v0.3.0
