apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: discord
images:
- name: immersion-bot
  newName: ghcr.io/brigadasos/immersion-bot
  newTag: a950b9a7db1f2e226c3f9ea2fc083bd09c0e6ab4
