apiVersion: v1
kind: Service
metadata:
  labels:
    app: immersion-bot
  name: immersion-bot
spec:
  ports:
    - name: http
      port: 8080
      targetedPort: http
  selector:
    app: immersion-bot
  type: ClusterIP
